import Head from 'next/head'
import styles from '../styles/Home.module.css'
import io from 'socket.io-client'
import { useEffect, useState } from 'react'
let socket

export default function Home() {
  const [input, setInput] = useState('')

  useEffect(() => {socketInitializer()}, [])

  const socketInitializer = async () => {
    await fetch('/api/socket')
    socket = io()

    socket.on('connect', () => {
      console.log('connected')
    })

    socket.on('update-input', msg => {
      setInput(msg)
    })
  }

  const onChangeHandler = (e) => {
    console.log("new message")
    setInput(e.target.value)
    socket.emit('input-change', e.target.value)
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <input
          placeholder="Type something"
          value={input}
          onChange={onChangeHandler}
        />
      </main>
    </>
  )
}
